# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

project_name: scimply

before:
  hooks:
    - go mod tidy
    - go generate ./...

snapshot:
  version_template: "{{ incpatch .Version }}-next"

gomod:
  proxy: true

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: scimply
    binary: scimply
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

universal_binaries:
  - id: scimply-universal
    ids:
      - scimply
    replace: true

checksum:
  name_template: "checksums.txt"

source:
  enabled: true

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - README.md
      - LICENSE

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ if .Logins }} ({{ .Logins | englishJoin }}){{ end }}"
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 1
    - title: "Other"
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore\(deps\): '
      - '^(build|ci): '
      - Merge pull request
      - Merge branch

milestones:
  - close: true

release:
  name_template: "v{{ .Version }}"

dockers_v2:
  - id: scimply-dockerhub
    dockerfile: .docker/Dockerfile-goreleaser
    images:
      - "cerberauth/scimply"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7

  - id: scimply-ghcr
    dockerfile: .docker/Dockerfile-goreleaser
    images:
      - "ghcr.io/cerberauth/scimply"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - "--yes"
