FROM gcr.io/distroless/static-debian12:nonroot

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

COPY --chown=nonroot:nonroot ${TARGETOS}/${TARGETARCH}${TARGETVARIANT:+/$TARGETVARIANT}/scimply /usr/bin/scimply

ENTRYPOINT ["/usr/bin/scimply"]
